# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160402_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
    ]
