# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160402_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume_language',
            name='language',
        ),
        migrations.RemoveField(
            model_name='resume_language',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='resume_skill',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='resume_skill',
            name='skill',
        ),
        migrations.AddField(
            model_name='resume',
            name='language',
            field=models.ManyToManyField(to='website.Language'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skill',
            field=models.ManyToManyField(to='website.Skill'),
        ),
        migrations.DeleteModel(
            name='Resume_language',
        ),
        migrations.DeleteModel(
            name='Resume_skill',
        ),
    ]
