# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160402_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Language')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Resume')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Skill')),
            ],
        ),
    ]
