# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_resume_language_resume_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume_language',
            name='language',
        ),
        migrations.RemoveField(
            model_name='resume_language',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='resume_skill',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='resume_skill',
            name='skill',
        ),
        migrations.DeleteModel(
            name='Resume_language',
        ),
        migrations.DeleteModel(
            name='Resume_skill',
        ),
    ]
