# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20160402_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='native_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
