# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_language_native_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='native_name',
            new_name='code',
        ),
    ]
