# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20160402_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=2),
        ),
    ]
