# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20160402_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Experience'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
