# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20160408_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(upload_to='upload/project-pictures'),
        ),
    ]
