# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20160408_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_image',
            name='thumb_url',
            field=models.ImageField(upload_to='project-pictures', verbose_name='Thumbnail URL'),
        ),
        migrations.AlterField(
            model_name='project_image',
            name='url',
            field=models.ImageField(upload_to='project-pictures'),
        ),
    ]
