# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20160408_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_image',
            old_name='url',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='project_image',
            name='thumb_url',
        ),
        migrations.AddField(
            model_name='project_image',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='project-pictures'),
        ),
    ]
