# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20160408_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_image',
            name='comment',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
