# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 02:24
from __future__ import unicode_literals

from django.db import migrations
import django_thumbs.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20160408_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_image',
            name='image',
            field=django_thumbs.db.models.ImageWithThumbsField(upload_to='project-pictures'),
        ),
    ]
